# Generated by Django 4.1.5 on 2023-01-28 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_book_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={},
        ),
    ]
