# Generated by Django 4.1.5 on 2023-01-31 19:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_alter_book_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="date_creation",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
