# Generated by Django 4.1.5 on 2023-02-02 17:13

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_book_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(
                blank=True,
                storage=gdstorage.storage.GoogleDriveStorage(),
                upload_to="BookstoreCovers/",
            ),
        ),
    ]
